#FROM nginx
#LABEL "Project"="Vprofile"
#LABEL "Author"="Imran"

#RUN rm -rf /etc/nginx/conf.d/default.conf
#COPY nginvproapp.conf /etc/nginx/conf.d/vproapp.conf

FROM nginx
LABEL "Project"="Vprofile"
LABEL "Author"="Arbaz"
RUN rm -rf /etc/nginx/conf.d/default.conf
COPY nginvproapp.conf /etc/nginx/conf.d/vproapp.conf